#!/bin/bash

app_dir="/var/www/dbdMVC2"
doc_dir="/var/www/vhosts/dbdmvc.com/dbdApp/assets/documentation/"
excludes=".svn/,Smarty-2.6.26/,FirePHPCore-0.3.2/"
php_doc="/usr/bin/phpdoc"

#prepare public html docs
rm -rf ${doc_dir}html/public/*
php ${php_doc} -t ${doc_dir}html/public -d ${app_dir} -i ${excludes} -o HTML:Smarty:DBD -ti dbdMVC Public Documentation -dn dbdMVC

#prepare private html docs
rm -rf ${doc_dir}html/private/*
php ${php_doc} -t ${doc_dir}html/private -d ${app_dir} -i ${excludes} -o HTML:Smarty:DBD -ti dbdMVC Private Documentation -dn dbdMVC -pp on -s on
